//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AISpec) DeepCopyInto(out *AISpec) {
	*out = *in
	if in.Anthropic != nil {
		in, out := &in.Anthropic, &out.Anthropic
		*out = new(AnthropicSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenAI != nil {
		in, out := &in.OpenAI, &out.OpenAI
		*out = new(OpenAISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenAICompatible != nil {
		in, out := &in.OpenAICompatible, &out.OpenAICompatible
		*out = new(OpenAICompatibleSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AISpec.
func (in *AISpec) DeepCopy() *AISpec {
	if in == nil {
		return nil
	}
	out := new(AISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentTLSSpec) DeepCopyInto(out *AgentTLSSpec) {
	*out = *in
	if in.CASecret != nil {
		in, out := &in.CASecret, &out.CASecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentTLSSpec.
func (in *AgentTLSSpec) DeepCopy() *AgentTLSSpec {
	if in == nil {
		return nil
	}
	out := new(AgentTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentsOnlySpec) DeepCopyInto(out *AgentsOnlySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentsOnlySpec.
func (in *AgentsOnlySpec) DeepCopy() *AgentsOnlySpec {
	if in == nil {
		return nil
	}
	out := new(AgentsOnlySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSourceSpec) DeepCopyInto(out *AlertSourceSpec) {
	*out = *in
	if in.Check != nil {
		in, out := &in.Check, &out.Check
		*out = new(CheckSourceSpec)
		**out = **in
	}
	if in.LogPattern != nil {
		in, out := &in.LogPattern, &out.LogPattern
		*out = new(LogPatternSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KubernetesEvents != nil {
		in, out := &in.KubernetesEvents, &out.KubernetesEvents
		*out = new(KubernetesEventsSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PromQL != nil {
		in, out := &in.PromQL, &out.PromQL
		*out = new(PromQLSourceSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSourceSpec.
func (in *AlertSourceSpec) DeepCopy() *AlertSourceSpec {
	if in == nil {
		return nil
	}
	out := new(AlertSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertTemplatesSpec) DeepCopyInto(out *AlertTemplatesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertTemplatesSpec.
func (in *AlertTemplatesSpec) DeepCopy() *AlertTemplatesSpec {
	if in == nil {
		return nil
	}
	out := new(AlertTemplatesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertingRuleSpec) DeepCopyInto(out *AlertingRuleSpec) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(AlertSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(AppSelectorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Severity != nil {
		in, out := &in.Severity, &out.Severity
		*out = new(string)
		**out = **in
	}
	if in.For != nil {
		in, out := &in.For, &out.For
		*out = new(string)
		**out = **in
	}
	if in.KeepFiringFor != nil {
		in, out := &in.KeepFiringFor, &out.KeepFiringFor
		*out = new(string)
		**out = **in
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = new(AlertTemplatesSpec)
		**out = **in
	}
	if in.NotificationCategory != nil {
		in, out := &in.NotificationCategory, &out.NotificationCategory
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertingRuleSpec.
func (in *AlertingRuleSpec) DeepCopy() *AlertingRuleSpec {
	if in == nil {
		return nil
	}
	out := new(AlertingRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnthropicSpec) DeepCopyInto(out *AnthropicSpec) {
	*out = *in
	if in.APIKeySecret != nil {
		in, out := &in.APIKeySecret, &out.APIKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnthropicSpec.
func (in *AnthropicSpec) DeepCopy() *AnthropicSpec {
	if in == nil {
		return nil
	}
	out := new(AnthropicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiKeySpec) DeepCopyInto(out *ApiKeySpec) {
	*out = *in
	if in.KeySecret != nil {
		in, out := &in.KeySecret, &out.KeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiKeySpec.
func (in *ApiKeySpec) DeepCopy() *ApiKeySpec {
	if in == nil {
		return nil
	}
	out := new(ApiKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppSelectorSpec) DeepCopyInto(out *AppSelectorSpec) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApplicationIdPatterns != nil {
		in, out := &in.ApplicationIdPatterns, &out.ApplicationIdPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppSelectorSpec.
func (in *AppSelectorSpec) DeepCopy() *AppSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(AppSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCategoryNotificationSettingsAlertsSpec) DeepCopyInto(out *ApplicationCategoryNotificationSettingsAlertsSpec) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(ApplicationCategoryNotificationSettingsSlackSpec)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = new(ApplicationCategoryNotificationSettingsTeamsSpec)
		**out = **in
	}
	if in.Pagerduty != nil {
		in, out := &in.Pagerduty, &out.Pagerduty
		*out = new(ApplicationCategoryNotificationSettingsPagerdutySpec)
		**out = **in
	}
	if in.Opsgenie != nil {
		in, out := &in.Opsgenie, &out.Opsgenie
		*out = new(ApplicationCategoryNotificationSettingsOpsgenieSpec)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(ApplicationCategoryNotificationSettingsWebhookSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCategoryNotificationSettingsAlertsSpec.
func (in *ApplicationCategoryNotificationSettingsAlertsSpec) DeepCopy() *ApplicationCategoryNotificationSettingsAlertsSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCategoryNotificationSettingsAlertsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCategoryNotificationSettingsDeploymentsSpec) DeepCopyInto(out *ApplicationCategoryNotificationSettingsDeploymentsSpec) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(ApplicationCategoryNotificationSettingsSlackSpec)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = new(ApplicationCategoryNotificationSettingsTeamsSpec)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(ApplicationCategoryNotificationSettingsWebhookSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCategoryNotificationSettingsDeploymentsSpec.
func (in *ApplicationCategoryNotificationSettingsDeploymentsSpec) DeepCopy() *ApplicationCategoryNotificationSettingsDeploymentsSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCategoryNotificationSettingsDeploymentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCategoryNotificationSettingsIncidentsSpec) DeepCopyInto(out *ApplicationCategoryNotificationSettingsIncidentsSpec) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(ApplicationCategoryNotificationSettingsSlackSpec)
		**out = **in
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = new(ApplicationCategoryNotificationSettingsTeamsSpec)
		**out = **in
	}
	if in.Pagerduty != nil {
		in, out := &in.Pagerduty, &out.Pagerduty
		*out = new(ApplicationCategoryNotificationSettingsPagerdutySpec)
		**out = **in
	}
	if in.Opsgenie != nil {
		in, out := &in.Opsgenie, &out.Opsgenie
		*out = new(ApplicationCategoryNotificationSettingsOpsgenieSpec)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(ApplicationCategoryNotificationSettingsWebhookSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCategoryNotificationSettingsIncidentsSpec.
func (in *ApplicationCategoryNotificationSettingsIncidentsSpec) DeepCopy() *ApplicationCategoryNotificationSettingsIncidentsSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCategoryNotificationSettingsIncidentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCategoryNotificationSettingsOpsgenieSpec) DeepCopyInto(out *ApplicationCategoryNotificationSettingsOpsgenieSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCategoryNotificationSettingsOpsgenieSpec.
func (in *ApplicationCategoryNotificationSettingsOpsgenieSpec) DeepCopy() *ApplicationCategoryNotificationSettingsOpsgenieSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCategoryNotificationSettingsOpsgenieSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCategoryNotificationSettingsPagerdutySpec) DeepCopyInto(out *ApplicationCategoryNotificationSettingsPagerdutySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCategoryNotificationSettingsPagerdutySpec.
func (in *ApplicationCategoryNotificationSettingsPagerdutySpec) DeepCopy() *ApplicationCategoryNotificationSettingsPagerdutySpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCategoryNotificationSettingsPagerdutySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCategoryNotificationSettingsSlackSpec) DeepCopyInto(out *ApplicationCategoryNotificationSettingsSlackSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCategoryNotificationSettingsSlackSpec.
func (in *ApplicationCategoryNotificationSettingsSlackSpec) DeepCopy() *ApplicationCategoryNotificationSettingsSlackSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCategoryNotificationSettingsSlackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCategoryNotificationSettingsSpec) DeepCopyInto(out *ApplicationCategoryNotificationSettingsSpec) {
	*out = *in
	in.Incidents.DeepCopyInto(&out.Incidents)
	in.Deployments.DeepCopyInto(&out.Deployments)
	in.Alerts.DeepCopyInto(&out.Alerts)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCategoryNotificationSettingsSpec.
func (in *ApplicationCategoryNotificationSettingsSpec) DeepCopy() *ApplicationCategoryNotificationSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCategoryNotificationSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCategoryNotificationSettingsTeamsSpec) DeepCopyInto(out *ApplicationCategoryNotificationSettingsTeamsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCategoryNotificationSettingsTeamsSpec.
func (in *ApplicationCategoryNotificationSettingsTeamsSpec) DeepCopy() *ApplicationCategoryNotificationSettingsTeamsSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCategoryNotificationSettingsTeamsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCategoryNotificationSettingsWebhookSpec) DeepCopyInto(out *ApplicationCategoryNotificationSettingsWebhookSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCategoryNotificationSettingsWebhookSpec.
func (in *ApplicationCategoryNotificationSettingsWebhookSpec) DeepCopy() *ApplicationCategoryNotificationSettingsWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCategoryNotificationSettingsWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationCategorySpec) DeepCopyInto(out *ApplicationCategorySpec) {
	*out = *in
	if in.CustomPatterns != nil {
		in, out := &in.CustomPatterns, &out.CustomPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.NotificationSettings.DeepCopyInto(&out.NotificationSettings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationCategorySpec.
func (in *ApplicationCategorySpec) DeepCopy() *ApplicationCategorySpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationCategorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthSpec) DeepCopyInto(out *BasicAuthSpec) {
	*out = *in
	if in.PasswordSecret != nil {
		in, out := &in.PasswordSecret, &out.PasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthSpec.
func (in *BasicAuthSpec) DeepCopy() *BasicAuthSpec {
	if in == nil {
		return nil
	}
	out := new(BasicAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckSourceSpec) DeepCopyInto(out *CheckSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckSourceSpec.
func (in *CheckSourceSpec) DeepCopy() *CheckSourceSpec {
	if in == nil {
		return nil
	}
	out := new(CheckSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickhouseKeeperSpec) DeepCopyInto(out *ClickhouseKeeperSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Image.DeepCopyInto(&out.Image)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickhouseKeeperSpec.
func (in *ClickhouseKeeperSpec) DeepCopy() *ClickhouseKeeperSpec {
	if in == nil {
		return nil
	}
	out := new(ClickhouseKeeperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickhouseS3Spec) DeepCopyInto(out *ClickhouseS3Spec) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(S3Credentials)
		(*in).DeepCopyInto(*out)
	}
	out.CacheSize = in.CacheSize.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickhouseS3Spec.
func (in *ClickhouseS3Spec) DeepCopy() *ClickhouseS3Spec {
	if in == nil {
		return nil
	}
	out := new(ClickhouseS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickhouseSpec) DeepCopyInto(out *ClickhouseSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Image.DeepCopyInto(&out.Image)
	in.Keeper.DeepCopyInto(&out.Keeper)
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(ClickhouseS3Spec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickhouseSpec.
func (in *ClickhouseSpec) DeepCopy() *ClickhouseSpec {
	if in == nil {
		return nil
	}
	out := new(ClickhouseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAgentSpec) DeepCopyInto(out *ClusterAgentSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Image.DeepCopyInto(&out.Image)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(AgentTLSSpec)
		(*in).DeepCopyInto(*out)
	}
	in.KubeStateMetrics.DeepCopyInto(&out.KubeStateMetrics)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAgentSpec.
func (in *ClusterAgentSpec) DeepCopy() *ClusterAgentSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityEditionSpec) DeepCopyInto(out *CommunityEditionSpec) {
	*out = *in
	in.Image.DeepCopyInto(&out.Image)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityEditionSpec.
func (in *CommunityEditionSpec) DeepCopy() *CommunityEditionSpec {
	if in == nil {
		return nil
	}
	out := new(CommunityEditionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Coroot) DeepCopyInto(out *Coroot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Coroot.
func (in *Coroot) DeepCopy() *Coroot {
	if in == nil {
		return nil
	}
	out := new(Coroot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Coroot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorootCloudRCASpec) DeepCopyInto(out *CorootCloudRCASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorootCloudRCASpec.
func (in *CorootCloudRCASpec) DeepCopy() *CorootCloudRCASpec {
	if in == nil {
		return nil
	}
	out := new(CorootCloudRCASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorootCloudSpec) DeepCopyInto(out *CorootCloudSpec) {
	*out = *in
	if in.APIKeySecret != nil {
		in, out := &in.APIKeySecret, &out.APIKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RCA != nil {
		in, out := &in.RCA, &out.RCA
		*out = new(CorootCloudRCASpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorootCloudSpec.
func (in *CorootCloudSpec) DeepCopy() *CorootCloudSpec {
	if in == nil {
		return nil
	}
	out := new(CorootCloudSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorootList) DeepCopyInto(out *CorootList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Coroot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorootList.
func (in *CorootList) DeepCopy() *CorootList {
	if in == nil {
		return nil
	}
	out := new(CorootList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CorootList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorootSpec) DeepCopyInto(out *CorootSpec) {
	*out = *in
	if in.AuthBootstrapAdminPasswordSecret != nil {
		in, out := &in.AuthBootstrapAdminPasswordSecret, &out.AuthBootstrapAdminPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	out.GRPC = in.GRPC
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CommunityEdition.DeepCopyInto(&out.CommunityEdition)
	if in.EnterpriseEdition != nil {
		in, out := &in.EnterpriseEdition, &out.EnterpriseEdition
		*out = new(EnterpriseEditionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentsOnly != nil {
		in, out := &in.AgentsOnly, &out.AgentsOnly
		*out = new(AgentsOnlySpec)
		**out = **in
	}
	in.Service.DeepCopyInto(&out.Service)
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ApiKeySecret != nil {
		in, out := &in.ApiKeySecret, &out.ApiKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	in.NodeAgent.DeepCopyInto(&out.NodeAgent)
	in.ClusterAgent.DeepCopyInto(&out.ClusterAgent)
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	if in.ExternalPrometheus != nil {
		in, out := &in.ExternalPrometheus, &out.ExternalPrometheus
		*out = new(ExternalPrometheusSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Clickhouse.DeepCopyInto(&out.Clickhouse)
	if in.ExternalClickhouse != nil {
		in, out := &in.ExternalClickhouse, &out.ExternalClickhouse
		*out = new(ExternalClickhouseSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CorootCloud != nil {
		in, out := &in.CorootCloud, &out.CorootCloud
		*out = new(CorootCloudSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]ProjectSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SSO != nil {
		in, out := &in.SSO, &out.SSO
		*out = new(SSOSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(AISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorootSpec.
func (in *CorootSpec) DeepCopy() *CorootSpec {
	if in == nil {
		return nil
	}
	out := new(CorootSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorootStatus) DeepCopyInto(out *CorootStatus) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorootStatus.
func (in *CorootStatus) DeepCopy() *CorootStatus {
	if in == nil {
		return nil
	}
	out := new(CorootStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomApplicationSpec) DeepCopyInto(out *CustomApplicationSpec) {
	*out = *in
	if in.InstancePatterns != nil {
		in, out := &in.InstancePatterns, &out.InstancePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomApplicationSpec.
func (in *CustomApplicationSpec) DeepCopy() *CustomApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(CustomApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfProfilerSpec) DeepCopyInto(out *EbpfProfilerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfProfilerSpec.
func (in *EbpfProfilerSpec) DeepCopy() *EbpfProfilerSpec {
	if in == nil {
		return nil
	}
	out := new(EbpfProfilerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbpfTracerSpec) DeepCopyInto(out *EbpfTracerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbpfTracerSpec.
func (in *EbpfTracerSpec) DeepCopy() *EbpfTracerSpec {
	if in == nil {
		return nil
	}
	out := new(EbpfTracerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseEditionSpec) DeepCopyInto(out *EnterpriseEditionSpec) {
	*out = *in
	if in.LicenseKeySecret != nil {
		in, out := &in.LicenseKeySecret, &out.LicenseKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	in.Image.DeepCopyInto(&out.Image)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseEditionSpec.
func (in *EnterpriseEditionSpec) DeepCopy() *EnterpriseEditionSpec {
	if in == nil {
		return nil
	}
	out := new(EnterpriseEditionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalClickhouseSpec) DeepCopyInto(out *ExternalClickhouseSpec) {
	*out = *in
	if in.PasswordSecret != nil {
		in, out := &in.PasswordSecret, &out.PasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalClickhouseSpec.
func (in *ExternalClickhouseSpec) DeepCopy() *ExternalClickhouseSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalClickhouseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPrometheusSpec) DeepCopyInto(out *ExternalPrometheusSpec) {
	*out = *in
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomHeaders != nil {
		in, out := &in.CustomHeaders, &out.CustomHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPrometheusSpec.
func (in *ExternalPrometheusSpec) DeepCopy() *ExternalPrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalPrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GRPCSpec) DeepCopyInto(out *GRPCSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GRPCSpec.
func (in *GRPCSpec) DeepCopy() *GRPCSpec {
	if in == nil {
		return nil
	}
	out := new(GRPCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderSpec) DeepCopyInto(out *HeaderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderSpec.
func (in *HeaderSpec) DeepCopy() *HeaderSpec {
	if in == nil {
		return nil
	}
	out := new(HeaderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(networkingv1.IngressTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InspectionOverrides) DeepCopyInto(out *InspectionOverrides) {
	*out = *in
	if in.SLOAvailability != nil {
		in, out := &in.SLOAvailability, &out.SLOAvailability
		*out = make([]SLOAvailabilityOverride, len(*in))
		copy(*out, *in)
	}
	if in.SLOLatency != nil {
		in, out := &in.SLOLatency, &out.SLOLatency
		*out = make([]SLOLatencyOverride, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InspectionOverrides.
func (in *InspectionOverrides) DeepCopy() *InspectionOverrides {
	if in == nil {
		return nil
	}
	out := new(InspectionOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeStateMetricsSpec) DeepCopyInto(out *KubeStateMetricsSpec) {
	*out = *in
	in.Image.DeepCopyInto(&out.Image)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeStateMetricsSpec.
func (in *KubeStateMetricsSpec) DeepCopy() *KubeStateMetricsSpec {
	if in == nil {
		return nil
	}
	out := new(KubeStateMetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesEventsSourceSpec) DeepCopyInto(out *KubernetesEventsSourceSpec) {
	*out = *in
	if in.MinCount != nil {
		in, out := &in.MinCount, &out.MinCount
		*out = new(int)
		**out = **in
	}
	if in.MaxAlertsPerApp != nil {
		in, out := &in.MaxAlertsPerApp, &out.MaxAlertsPerApp
		*out = new(int)
		**out = **in
	}
	if in.EvaluateWithAi != nil {
		in, out := &in.EvaluateWithAi, &out.EvaluateWithAi
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesEventsSourceSpec.
func (in *KubernetesEventsSourceSpec) DeepCopy() *KubernetesEventsSourceSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesEventsSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogCollectorSpec) DeepCopyInto(out *LogCollectorSpec) {
	*out = *in
	if in.CollectLogBasedMetrics != nil {
		in, out := &in.CollectLogBasedMetrics, &out.CollectLogBasedMetrics
		*out = new(bool)
		**out = **in
	}
	if in.CollectLogEntries != nil {
		in, out := &in.CollectLogEntries, &out.CollectLogEntries
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogCollectorSpec.
func (in *LogCollectorSpec) DeepCopy() *LogCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(LogCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogPatternSourceSpec) DeepCopyInto(out *LogPatternSourceSpec) {
	*out = *in
	if in.Severities != nil {
		in, out := &in.Severities, &out.Severities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MinCount != nil {
		in, out := &in.MinCount, &out.MinCount
		*out = new(int)
		**out = **in
	}
	if in.MaxAlertsPerApp != nil {
		in, out := &in.MaxAlertsPerApp, &out.MaxAlertsPerApp
		*out = new(int)
		**out = **in
	}
	if in.EvaluateWithAi != nil {
		in, out := &in.EvaluateWithAi, &out.EvaluateWithAi
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogPatternSourceSpec.
func (in *LogPatternSourceSpec) DeepCopy() *LogPatternSourceSpec {
	if in == nil {
		return nil
	}
	out := new(LogPatternSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAgentSpec) DeepCopyInto(out *NodeAgentSpec) {
	*out = *in
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Image.DeepCopyInto(&out.Image)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(AgentTLSSpec)
		(*in).DeepCopyInto(*out)
	}
	in.LogCollector.DeepCopyInto(&out.LogCollector)
	in.EbpfTracer.DeepCopyInto(&out.EbpfTracer)
	in.EbpfProfiler.DeepCopyInto(&out.EbpfProfiler)
	if in.TrackPublicNetworks != nil {
		in, out := &in.TrackPublicNetworks, &out.TrackPublicNetworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAgentSpec.
func (in *NodeAgentSpec) DeepCopy() *NodeAgentSpec {
	if in == nil {
		return nil
	}
	out := new(NodeAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationIntegrationOpsgenieSpec) DeepCopyInto(out *NotificationIntegrationOpsgenieSpec) {
	*out = *in
	if in.ApiKeySecret != nil {
		in, out := &in.ApiKeySecret, &out.ApiKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationIntegrationOpsgenieSpec.
func (in *NotificationIntegrationOpsgenieSpec) DeepCopy() *NotificationIntegrationOpsgenieSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationIntegrationOpsgenieSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationIntegrationPagerdutySpec) DeepCopyInto(out *NotificationIntegrationPagerdutySpec) {
	*out = *in
	if in.IntegrationKeySecret != nil {
		in, out := &in.IntegrationKeySecret, &out.IntegrationKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationIntegrationPagerdutySpec.
func (in *NotificationIntegrationPagerdutySpec) DeepCopy() *NotificationIntegrationPagerdutySpec {
	if in == nil {
		return nil
	}
	out := new(NotificationIntegrationPagerdutySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationIntegrationSlackSpec) DeepCopyInto(out *NotificationIntegrationSlackSpec) {
	*out = *in
	if in.TokenSecret != nil {
		in, out := &in.TokenSecret, &out.TokenSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationIntegrationSlackSpec.
func (in *NotificationIntegrationSlackSpec) DeepCopy() *NotificationIntegrationSlackSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationIntegrationSlackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationIntegrationTeamsSpec) DeepCopyInto(out *NotificationIntegrationTeamsSpec) {
	*out = *in
	if in.WebhookURLSecret != nil {
		in, out := &in.WebhookURLSecret, &out.WebhookURLSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationIntegrationTeamsSpec.
func (in *NotificationIntegrationTeamsSpec) DeepCopy() *NotificationIntegrationTeamsSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationIntegrationTeamsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationIntegrationWebhookSpec) DeepCopyInto(out *NotificationIntegrationWebhookSpec) {
	*out = *in
	if in.BasicAuth != nil {
		in, out := &in.BasicAuth, &out.BasicAuth
		*out = new(BasicAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomHeaders != nil {
		in, out := &in.CustomHeaders, &out.CustomHeaders
		*out = make([]HeaderSpec, len(*in))
		copy(*out, *in)
	}
	if in.CustomFields != nil {
		in, out := &in.CustomFields, &out.CustomFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationIntegrationWebhookSpec.
func (in *NotificationIntegrationWebhookSpec) DeepCopy() *NotificationIntegrationWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationIntegrationWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationIntegrationsSpec) DeepCopyInto(out *NotificationIntegrationsSpec) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(NotificationIntegrationSlackSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = new(NotificationIntegrationTeamsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Pagerduty != nil {
		in, out := &in.Pagerduty, &out.Pagerduty
		*out = new(NotificationIntegrationPagerdutySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Opsgenie != nil {
		in, out := &in.Opsgenie, &out.Opsgenie
		*out = new(NotificationIntegrationOpsgenieSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(NotificationIntegrationWebhookSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationIntegrationsSpec.
func (in *NotificationIntegrationsSpec) DeepCopy() *NotificationIntegrationsSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationIntegrationsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAICompatibleSpec) DeepCopyInto(out *OpenAICompatibleSpec) {
	*out = *in
	if in.APIKeySecret != nil {
		in, out := &in.APIKeySecret, &out.APIKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAICompatibleSpec.
func (in *OpenAICompatibleSpec) DeepCopy() *OpenAICompatibleSpec {
	if in == nil {
		return nil
	}
	out := new(OpenAICompatibleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAISpec) DeepCopyInto(out *OpenAISpec) {
	*out = *in
	if in.APIKeySecret != nil {
		in, out := &in.APIKeySecret, &out.APIKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAISpec.
func (in *OpenAISpec) DeepCopy() *OpenAISpec {
	if in == nil {
		return nil
	}
	out := new(OpenAISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresSpec) DeepCopyInto(out *PostgresSpec) {
	*out = *in
	if in.PasswordSecret != nil {
		in, out := &in.PasswordSecret, &out.PasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresSpec.
func (in *PostgresSpec) DeepCopy() *PostgresSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	if in.MemberProjects != nil {
		in, out := &in.MemberProjects, &out.MemberProjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RemoteCoroot != nil {
		in, out := &in.RemoteCoroot, &out.RemoteCoroot
		*out = new(RemoteCorootSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ApiKeys != nil {
		in, out := &in.ApiKeys, &out.ApiKeys
		*out = make([]ApiKeySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotificationIntegrations != nil {
		in, out := &in.NotificationIntegrations, &out.NotificationIntegrations
		*out = new(NotificationIntegrationsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationCategories != nil {
		in, out := &in.ApplicationCategories, &out.ApplicationCategories
		*out = make([]ApplicationCategorySpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomApplications != nil {
		in, out := &in.CustomApplications, &out.CustomApplications
		*out = make([]CustomApplicationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertingRules != nil {
		in, out := &in.AlertingRules, &out.AlertingRules
		*out = make([]AlertingRuleSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InspectionOverrides != nil {
		in, out := &in.InspectionOverrides, &out.InspectionOverrides
		*out = new(InspectionOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromQLSourceSpec) DeepCopyInto(out *PromQLSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromQLSourceSpec.
func (in *PromQLSourceSpec) DeepCopy() *PromQLSourceSpec {
	if in == nil {
		return nil
	}
	out := new(PromQLSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusSpec) DeepCopyInto(out *PrometheusSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Image.DeepCopyInto(&out.Image)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusSpec.
func (in *PrometheusSpec) DeepCopy() *PrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteCorootSpec) DeepCopyInto(out *RemoteCorootSpec) {
	*out = *in
	if in.ApiKeySecret != nil {
		in, out := &in.ApiKeySecret, &out.ApiKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteCorootSpec.
func (in *RemoteCorootSpec) DeepCopy() *RemoteCorootSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteCorootSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Credentials) DeepCopyInto(out *S3Credentials) {
	*out = *in
	if in.AccessKeyID != nil {
		in, out := &in.AccessKeyID, &out.AccessKeyID
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretAccessKey != nil {
		in, out := &in.SecretAccessKey, &out.SecretAccessKey
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Credentials.
func (in *S3Credentials) DeepCopy() *S3Credentials {
	if in == nil {
		return nil
	}
	out := new(S3Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOAvailabilityOverride) DeepCopyInto(out *SLOAvailabilityOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOAvailabilityOverride.
func (in *SLOAvailabilityOverride) DeepCopy() *SLOAvailabilityOverride {
	if in == nil {
		return nil
	}
	out := new(SLOAvailabilityOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOLatencyOverride) DeepCopyInto(out *SLOLatencyOverride) {
	*out = *in
	out.ObjectiveThreshold = in.ObjectiveThreshold
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOLatencyOverride.
func (in *SLOLatencyOverride) DeepCopy() *SLOLatencyOverride {
	if in == nil {
		return nil
	}
	out := new(SLOLatencyOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSOOIDCSpec) DeepCopyInto(out *SSOOIDCSpec) {
	*out = *in
	if in.ClientSecretSecret != nil {
		in, out := &in.ClientSecretSecret, &out.ClientSecretSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSOOIDCSpec.
func (in *SSOOIDCSpec) DeepCopy() *SSOOIDCSpec {
	if in == nil {
		return nil
	}
	out := new(SSOOIDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSOSAMLSpec) DeepCopyInto(out *SSOSAMLSpec) {
	*out = *in
	if in.MetadataSecret != nil {
		in, out := &in.MetadataSecret, &out.MetadataSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSOSAMLSpec.
func (in *SSOSAMLSpec) DeepCopy() *SSOSAMLSpec {
	if in == nil {
		return nil
	}
	out := new(SSOSAMLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSOSpec) DeepCopyInto(out *SSOSpec) {
	*out = *in
	if in.SAML != nil {
		in, out := &in.SAML, &out.SAML
		*out = new(SSOSAMLSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(SSOOIDCSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSOSpec.
func (in *SSOSpec) DeepCopy() *SSOSpec {
	if in == nil {
		return nil
	}
	out := new(SSOSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
	if in.CertSecret != nil {
		in, out := &in.CertSecret, &out.CertSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.KeySecret != nil {
		in, out := &in.KeySecret, &out.KeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}
