apiVersion: deploy.tel/v1
kind: Telemetry
metadata:
  name: telemetry
  namespace: telemetry
spec:
  tls:
    certSecret:
      name: telemetry-server-tls
      key: tls.crt
    keySecret:
      name: telemetry-server-tls
      key: tls.key
  
  httpDisabled: true
  
  apiKeySecret:
    name: telemetry-api-key
    key: key

  projects:
    - name: "My Cluster"
      apiKeys:
        - keySecret:
            name: telemetry-api-key
            key: key

  clusterAgent:
    tls:
      caSecret:
        name: telemetry-ca-cert
        key: ca.crt
      tlsSkipVerify: false

  nodeAgent:
    tls:
      caSecret:
        name: telemetry-ca-cert
        key: ca.crt
      tlsSkipVerify: false
