apiVersion: deploy.tel/v1
kind: Telemetry
metadata:
  name: telemetry
  namespace: telemetry
spec:
#  agentsOnly:
#    telemetryURL:
#  replicas: 1
  nodeAgent:
  clusterAgent:
  prometheus:
  clickhouse:
    shards: 1
    replicas: 1
    storage:
      size: 10Gi
